### ISSUE TITLE
Images in question are not showing

### ISSUE THREAD

**Issue by curiousnewb** [vtos/moodle-mod_adaptivequiz#10]
Hi,

thanks a lot for creating the plugin. 

In our question pool there is a question of the moodle type "drag and drop onto image" which uses a png file as an image. It is displayed correctly in the question preview from the question bank and also in a standard moodle quiz but does not show any image when coming up during an adaptive quiz attempt. The following error message came up:

![Error course module ID background image drag question](https://user-images.githubusercontent.com/116086435/196438883-b64beb51-6b11-46d1-9417-cb5dc82c9373.jpg)

**Comment by curiousnewb** [comment]
Under [Issue #4](https://github.com/vtos/moodle-mod_adaptivequiz/issues/4) a similar problem was already mentioned.

**Comment by vtos** [comment]
Thanks @curiousnewb for raising this issue once more.
This has been fixed on master and will appear in the new version release.
