### ISSUE TITLE
Link parameter missing

### ISSUE THREAD

**Issue by 0815-xyz** [vtos/moodle-mod_adaptivequiz#13]
Hi, 
please forgive me if this is not a bug but an issue related to our installation. But since the upgrade for Moddle 4 I'm running into an error when trying to follow the review attempt link from within the question analysis. It reads: 
A required parameter (attempt) was missing
and the explanation goes:
A required parameter (id) was missing.
This error happens when a webpage expects a parameter to be passed from another page (by post or cookie), and it fails to do so.
This happens sometimes when user session times out, due to inactivity, or when an URL that needs that mandatory parameter is instead directly typed in URL bar or invoked from browser bookmarks, like the SCORM Player page not being launched from a link in the course page.

**Comment by vtos** [comment]
HI @0815-xyz , could you please more exact about the link? You can post a screen shot to make it clear. As on the questions analysis page I cannot see a 'review attempt link', just links to follow to a specific question to review. Thank you!

**Comment by 0815-xyz** [comment]
Hi,
I'm sorry I wasn't clear enough. Yes, after following the link to the question to be reviewed you get another link to review the attempts of that question:
![review attempt link](https://user-images.githubusercontent.com/116554947/215071404-06544931-7144-4b9c-b7e1-3a597333537a.png)
where following one of the links in our case leads to .../moodle/mod/adaptivequiz/reviewattempt.php?cmid=100&uniqueid=89&userid=2 with an error message because the attempt parameter is missing.
Thank you for attending to it.
Konstanze

**Comment by vtos** [comment]
Confirming this behavior. The link was missed when changing how attempts are referenced by their ID. Will be fixed in the nearest update. Thanks for reporting, Konstanze @0815-xyz!

**Comment by vtos** [comment]
Fixed on the master branch, will be included in the nearest plugin release.
