### ISSUE TITLE
Deprecated Error Appearing - Moodle 4.1.1

### ISSUE THREAD

**Issue by UncleRaymondo** [vtos/moodle-mod_adaptivequiz#14]
Hi Team,

FYI - If someone can fix these, that'll be great :)

```
- Deprecated: Required parameter $adaptivequiz follows optional parameter $instance in /opt/sites/lms.thalescyber.academy/mod/adaptivequiz/lib.php on line 117
- Deprecated: Required parameter $adaptivequiz follows optional parameter $instance in /opt/sites/lms.thalescyber.academy/mod/adaptivequiz/lib.php on line 137
```

Cheers,
Ray

**Comment by vtos** [comment]
Hi @UncleRaymondo , can you please specify where you're getting this deprecation reporting from?

**Comment by vtos** [comment]
@UncleRaymondo by the way, I've just noticed 4.1.1 mentioned in the issue's title. The plugin doesn't officially support 4.1 yet. It _may_ work there smoothly, but this hasn't been tested yet :slightly_smiling_face:

**Comment by vtos** [comment]
@UncleRaymondo came across this on the way, it's a part of the plugin's legacy code and basically is a coding style issue, it affects all plugin versions. Will be fixed soon, thanks for pointing out :+1:

**Comment by vtos** [comment]
Fixed on master, will be included in the nearest release. Thanks!
