### ISSUE TITLE
Listing attempts when implementing a catmodel subplugin

### ISSUE THREAD

**Issue by davidszkiba** [vtos/moodle-mod_adaptivequiz#18]
Hello!

Thanks a lot for your work on this plugin!

I am trying to implement a catmodel subplugin and while doing so, I realized that the previous attempts are not listed in the "Your previous attempts" section and in the "Individual user attempts report" if I do not specifically save new cat params in the `adaptive_cat_params` DB table. I added the following to the `post_create_attempt()` callback of my subplugin to save them:

```php
cat_model_params::create_new_for_attempt($attempt->read_attempt_data()->id);
```
My question is: do you plan to update your code so that subplugins won't need to add the cat_model_params by themselves or will it stay like it is now?

**Comment by vtos** [comment]
@davidszkiba 
Hi David,

Continuing with the attempts report when using a sub-plugin - a sub-plugin now can provide a link to its own attempts report by using a callback, please, see the updated README on both **catmodel_subplugin*** branches. Cheers!

**Comment by davidszkiba** [comment]
Hi Vitaly,

cool, thanks!
