### ISSUE TITLE
Attempt Graph / Answer Distribution Graph plots not displayed

### ISSUE THREAD

**Issue by 0815-xyz** [vtos/moodle-mod_adaptivequiz#19]
Hi Vitaly,

we are running your plugin on Moodle 3.11, Moodle 4.0 and Moodle 4.1. It is only on Moodle 4.1 that we have the problem of the plots for the Attempt Graph as well as the Answer Distribution Graph not being displayed. The error messages are 
![image](https://github.com/vtos/moodle-mod_adaptivequiz/assets/116554947/54b02fff-9193-4829-82f9-1cb80e50871d)
and 
![image](https://github.com/vtos/moodle-mod_adaptivequiz/assets/116554947/d9122a0d-f890-4a79-90bf-08435d90905d)
respectively.
Is this due to some changes that were done to Moodle 4.1? We'd really appreciate your help.

Konstanze

**Comment by 0815-xyz** [comment]
Hi,
It is PHP Version 7.4.3 on all of them.

**Comment by vtos** [comment]
@0815-xyz 
You guessed it right, this commit https://github.com/moodle/moodle/commit/710d0ef8f24813ed5a4b691f15b8431713470549 for the latest 4.1, which is 4.1.4 added `declare(strict_types=1);` to the graph lib. And it looks like some lines were missed to add explicit casting of what `round()` returns to an `int`.

I'll probably create an issue on Moodle Tracker for that.

**Comment by vtos** [comment]
Forgot to mention - in further versions these graphs will be replaced with [Chart js](https://www.chartjs.org) implementations, the work has already started :wink:

**Comment by 0815-xyz** [comment]
Thank you for the quick find and for keeping me updated🙋‍♀️

**Comment by UncleRaymondo** [comment]
Hello, 

Do we have any updates on this issue? We see the same issue (with a different but somewhat related error) on 4.1.9 and PHP 8.1.27

Much appreciated :)

Cheers,
Ray

**Comment by vtos** [comment]
Hi @UncleRaymondo,

I'm working on replacing the previous implementation of the graph (which does not work in Moodle 4.1.4 and higher) with the Chartjs implementation (the JavaScript library used by Moodle for charts to replace the previous implementations using graphlib).

Regards
Vitaly

**Comment by UncleRaymondo** [comment]
Hi @vtos 

Many thanks for your work on this plugin. Do you have a rough idea of when this replacement will be complete? I have two Moodle instances operating both 4.1.9 and 4.3.3 for two academies; this plugin is a great feature for them and one I always recommend when proposing LMSs to our clients :)

Cheers,
Ray

**Comment by vtos** [comment]
@UncleRaymondo I'm doing my best to release the new version (which is also supposed to work for Moodle 4.3 as well) by March.

**Comment by vtos** [comment]
Fixed on the master branch, will be applied to plugin's versions for Moodle 4.1 - 4.3.
