### ISSUE TITLE
Question Analysis button

### ISSUE THREAD

**Issue by caiadogithub** [vtos/moodle-mod_adaptivequiz#2]
Hi,

Moodle 3.11.4+
PostgreSQL 12
PHP 7.4
Ubuntu 20.04

When I click the "Question Analysis" button I got this error message:

![Firefox_Screenshot_2022-01-31T19-10-06 362Z](https://user-images.githubusercontent.com/23316275/151856988-1aa11a0a-4176-44c1-a9dd-33202ab4049c.png)

Ricardo

**Comment by vtos** [comment]
Hi @caiadogithub,
Could you please post particular quiz settings you're getting the error for? And could you track the flow to get the error - what account you're using, what preceding actions were, like, "I added a quiz, made an attempt/didn't make an attempt, navigated to the questions analysis" and so on. Hope that makes sense, this way we can reproduce the error way quicker. Thank you!

**Comment by caiadogithub** [comment]
![Firefox_Screenshot_2022-02-01T15-53-30 934Z](https://user-images.githubusercontent.com/23316275/152002487-83d02da0-cc50-49e8-874e-464b3e49371a.png)

**Comment by vtos** [comment]
Fixed in [2.0.1](https://github.com/vtos/moodle-mod_adaptivequiz/releases/tag/2.0.1) release, closing.
