### ISSUE TITLE
misplaced intro text in activity view / course view

### ISSUE THREAD

**Issue by ralferlebach** [vtos/moodle-mod_adaptivequiz#28]
Description:

when setting up a mod_adaptive and check "Show description on course page", the description (intro) does not appear in the course, but twice in the activity's view.php page.

Problem observed on Moodle versions 3.11, 4.0 and 4.3

Fixed by #27

**Comment by vtos** [comment]
@ralferlebach 
Hi, thank you for raising this and for your PR. It'll be reviewed and merged in the upcoming version. The new version is expected to be released by March and will officially support Moodle 4.1.4 and upwards. Cheers!

**Comment by ralferlebach** [comment]
Thanks @vtos,

great news, looking forward to the next Version in march. Also, this PR will also be already included in the PR that will come from Wunderbyte within the next days.

**Comment by ralferlebach** [comment]
It's included in PR #29, so I regard this Issue as closed.

**Comment by vtos** [comment]
Re-opened this one, as it'll be actually fixed in the upcoming new version. We should close an issue only when it's actually addressed in the main branch.

**Comment by vtos** [comment]
A tribute to https://github.com/vtos/moodle-mod_adaptivequiz/pull/27 to get this fixed.
