### ISSUE TITLE
Notice: did you remember to make the first column something unique in your call to get_records()?

### ISSUE THREAD

**Issue by vtos** [vtos/moodle-mod_adaptivequiz#3]
![image](https://user-images.githubusercontent.com/98814308/152133563-4ad7e02b-e6f6-4a6a-ab8e-ef41608afc4c.png)

_Originally posted by @amh-boston in https://github.com/vtos/moodle-mod_adaptivequiz/issues/1#issuecomment-1027774288_

**Comment by vtos** [comment]
@amh-boston Are you using the latest version (2.0.0) of the plugin when getting this? It looks to me like you're running the previous version (1.2.3 or something).

**Comment by vtos** [comment]
Well, disregard my previous comment :) Just trying to reproduce those notices.

**Comment by vtos** [comment]
Fixed in [2.0.1](https://github.com/vtos/moodle-mod_adaptivequiz/releases/tag/2.0.1) release, closing.

**Comment by amh-boston** [comment]
Hi, 
vtos the 2.0.1 release resolved the issue and question in the adaptive quiz is now appearing and working.
Now that I can see the questions in the quiz, the images in questions (.png & .jpg)are not showing.  I have loaded the same questions in a normal quiz then images show.
Any idea or advise?

**Comment by semteacher** [comment]
@amh-boston  I was working on this in my fork about 4 years ago and developed kind of solution:
https://github.com/semteacher/moodle-mod_adaptivequiz/commit/ed40ae3ebc25b1c098b285e87de8185bd9d8e2b1
Hope it could be helpful.

**Comment by vtos** [comment]
@amh-boston Hi Andrew,
I would suggest you create a new issue for that, as this is entirely unrelated to the current closed issue where we're commenting :)
Also, it would be a huge help if you attached some description of setting up such questions so I would easily reproduce it to see what's happening. Perhaps, we can merge the Andriy's @semteacher solution (if they don't mind :) ) after that to see if it works for the current plugin's version. Thank you!
