### ISSUE TITLE
Error on switching to single activity course format 

### ISSUE THREAD

**Issue by 0815-xyz** [vtos/moodle-mod_adaptivequiz#31]
Hi there,
I want to mention that to me personally this is not a top level problem but rather minor since you can avoid it by simply not going there (as long as you are warned). But I'll report it anyway, especially as it leaves you with the whole course settings inaccessible so that you can't even revert to the previous settings. I ran into this problem when switching the course format to "single activity format" and selecting "Adaptive Quiz" as the type of activity from the drop down menu. The error message reads:
![Error Course Format SingleActivity](https://github.com/vtos/moodle-mod_adaptivequiz/assets/116554947/43fcc98e-0e45-4f20-af68-d094b3d0ba05)
The adaptive quiz activity itself can still be used thereafter but as mentioned above one cannot revert this step as any click on the whole course menu (settings, participants, grades, reports etc.) only leads to the same error message. So you can neither go back to the old settings nor access any course information.

**Comment by vtos** [comment]
Thanks for logging this one. Every little thing in the plugin that breaks normal Moodle's flows should always be fixed, so, such reports are highly appreciated! It's a shame, but I've never tried the adaptive quiz activity in a single-activity course (and nor has anyone else as it seems, at least it's never been reported).
