### ISSUE TITLE
Review Attempt error on Question Analysis page

### ISSUE THREAD

**Issue by synnac** [vtos/moodle-mod_adaptivequiz#32]
On the Question Analysis page, click on any question, you can see the "Review Attempt" button. Click on it, you will get this error.
Adaptivequiz Version: 2.3.5
Moodle Version: 4.2.1

![image](https://github.com/vtos/moodle-mod_adaptivequiz/assets/88969475/e00679c3-995b-49e5-9e26-a738f6440d4b)

![屏幕截图 2024-04-05 100931](https://github.com/vtos/moodle-mod_adaptivequiz/assets/88969475/7e731279-103e-4ded-b6f9-bb886241cdc5)

**Comment by vtos** [comment]
Has been resolved already actually, just wasn't included in the previous versions - https://github.com/vtos/moodle-mod_adaptivequiz/issues/13

**Comment by vtos** [comment]
Will be included in the upcoming 2.3.6.
