### ISSUE TITLE
Skipping a level during test

### ISSUE THREAD

**Issue by conigonzalez** [vtos/moodle-mod_adaptivequiz#35]
Hi! Thank you so much for keeping this plugin working! 
I am currently applying a quiz to a group of students with the objective of knowing their level of English
We have had the issue of reoccurring skipped levels during the test.
We have for example the following settings:

Attempts allowed: Unlimited
Question pool: 195 questions, all on status ready (39x tagged adpq_1, 39x adpq_2, 39x adpq_3, 39x adpq_4, 39x adpq_5)
Starting level of difficulty: 2
Lowest level of difficulty: 1
Highest level of difficulty: 5
Show ability measure to students: Yes
Show quiz progress to students: Yes
Minimum number of questions: 30
Maximum number of questions: 35
Standard Error to stop: 3.65

As the students begin the test at level 2, if they get the question correct, they jump straight to level 4, almost always. This has caused a distortion in the results, having a lot of students ending up with results spread across level 4.
 
What causes this? It is something to to with the way the algorithm works or is it the settings we have established?

Thanks!!

**Comment by 0815-xyz** [comment]
Hi @conigonzalez,
I'm fully aware that your report is not addressed to me and I'm just a user like you. But I can give you the feedback that AFAIK the behaviour that you describe (jumping from starting level 2 to 4 after a correct answer when using difficulty levels 1 to 5) is actually absolutely normal. The algorithm takes into account your range of difficulty levels by incorporating the span (5) in a linear transformation before converting the parameters to the logit scale where the next difficulty level D is calculated by D = D + 2/L (where L is the number of administered questions). Therefore the level jumps will be higher at first but will become smaller step by step. If your students do not really perform consistently at level 4, but fail subsequent questions at level 4 (or even 3), their ability measure will drop again - especially as your minimum number of questions is 30.

**Comment by vtos** [comment]
@conigonzalez 
As also replied above, yes, that's the expected behavior. When the test begins, the algorithm tries to 'fumble' the precise (well, more or less) ability value. So it'll bump up or decrease the level while doing so. While going through more and more responses, such 'fumbling' starts to increment/decrement levels in smaller steps. But from the beginning it can be 'bumpy'.

**Comment by vtos** [comment]
Closing this, as this doesn't seem to have further questions/issues.
