### ISSUE TITLE
Question detail doesn't work

### ISSUE THREAD

**Issue by kebumenbolenk123** [vtos/moodle-mod_adaptivequiz#5]
On the Review Attemp page --> Question Details, when you will see the summary on the next page by clicking the number 2, it does not go to the next page but will go to the Attemp Summary.

**Comment by kebumenbolenk123** [comment]
![image](https://user-images.githubusercontent.com/102456654/160273682-073bb85b-bef9-4824-b431-4025a4333411.png)

 when you will see the summary on the next page by clicking the number 2, it does not go to the next page but will go to the Attemp Summary

**Comment by vtos** [comment]
Was fixed actually in one of the previous releases, closing.
