### ISSUE TITLE
There are three usages of the YUI module 'moodle-core-formchangechecker' which has been deprecated. It has been replaced with 'core_form/changechecker'

### ISSUE THREAD

**Issue by Julian-Tovar** [vtos/moodle-mod_adaptivequiz#9]
Good day. The YUI module 'moodle-core-formchangechecker' was deprecated and replaced by 'core_form/changechecker' in MDL-69918, there you can see examples of how to implement the replacement. This affects Moodle 4.0.

In mod_adaptivequiz, this deprecation has three instances:

- In `M.mod_adaptivequiz.init_attempt_form` found in 'mod/adaptivequiz/module.js:33' or https://github.com/vtos/moodle-mod_adaptivequiz/blob/MOODLE_400/module.js#L33
- In `\mod_adaptivequiz_renderer::adaptivequiz_get_js_module` found in 'mod/adaptivequiz/renderer.php:94' or https://github.com/vtos/moodle-mod_adaptivequiz/blob/MOODLE_400/renderer.php#L94
- In `\mod_adaptivequiz_renderer_testcase::test_adaptivequiz_get_js_module` found in 'mod/adaptivequiz/tests/renderer_test.php:78' or https://github.com/vtos/moodle-mod_adaptivequiz/blob/MOODLE_400/tests/renderer_test.php#L78

**Comment by vtos** [comment]
Hey @Julian-Tovar , thanks for reporting this! The update will be included in one of the nearest versions.

**Comment by vtos** [comment]
Pushed the change to the master branch.
